
module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    EDIT_ORDER: "EDIT_ORDER",
    ADD_CUSTOMER: "ADD_CUSTOMER",
    EDIT_CUSTOMER: "EDIT_CUSTOMER",
    BILL_DETAILS: "BILL_DETAILS",
    CONFIRM_ORDER: "CONFIRM_ORDER",
    INGRE_ORDER_DETAIL: "INGRE_ORDER_DETAIL",
    ADD_INGRE_ORDER: "ADD_INGRE_ORDER",
    EDIT_INGRE: "EDIT_INGRE",
    ADD_INGRE: "ADD_INGRE",
    ADD_FOOD: "ADD_FOOD",
    EDIT_FOOD: "EDIT_FOOD",
    USER_DETAIL: "USER_DETAIL",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    CANCEL_IG_ORDER: "CANCEL_IG_ORDER",
    CONFIRM_IG_ORDER: "CONFIRM_IG_ORDER",
    CANCEL_ORDER: "CANCEL_ORDER",
    REMOVE_CUSTOMER: "REMOVE_CUSTOMER",
  },
});
